name: perch_eye
description: Flutter plugin for PerchEye SDK (AAR)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.percheye.flutter
        pluginClass: PerchEyePlugin
